import React, { useEffect, useMemo, useState } from "react";
import { Link, useParams } from "react-router-dom";
import api from "../services/api";
import { AppLayout, EmptyState, ErrorState, LoadingState } from "../components/AppLayout";

const riskStyles = { CRITICAL: "bg-rose-100 text-rose-800", HIGH: "bg-orange-100 text-orange-800", MEDIUM: "bg-amber-100 text-amber-800", LOW: "bg-teal-100 text-teal-800", INFO: "bg-blue-100 text-blue-800" };
const risk = value => String(value || "LOW").toUpperCase();
const issueText = issue => issue.problem || issue.title || issue.message || "Potential issue detected";

export default function Review() {
  const { owner, repo, pr } = useParams(); const [files, setFiles] = useState([]); const [review, setReview] = useState(null); const [history, setHistory] = useState([]); const [loading, setLoading] = useState(true); const [analyzing, setAnalyzing] = useState(false); const [error, setError] = useState(""); const [selected, setSelected] = useState(0); const [copied, setCopied] = useState("");
  const params = { owner, repo, pr };
  const load = async () => { try { setLoading(true); setError(""); const [fileResult, historyResult] = await Promise.all([api.get(`/api/github/repositories/${owner}/${repo}/pull-requests/${pr}/files/`), api.get("/api/review/history/", { params })]); setFiles(fileResult.data.files || []); setHistory(historyResult.data.reviews || []); const latest = historyResult.data.reviews?.[0]; if (latest?.review) setReview(latest.review); } catch (e) { setError(e.response?.status === 401 ? "Your session has expired. Please sign in again." : "We couldn't load this Pull Request."); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [owner, repo, pr]);
  const runReview = async () => { try { setAnalyzing(true); setError(""); const result = await api.post("/api/review/review/", null, { params }); setReview(result.data.review || null); const updated = await api.get("/api/review/history/", { params }); setHistory(updated.data.reviews || []); } catch (e) { setError("The AI review could not be completed. Please try again."); } finally { setAnalyzing(false); } };
  const currentFile = files[selected]; const issues = review?.issues || []; const reviewRisk = risk(review?.risk_level); const score = review?.risk_score ?? review?.score ?? (review ? { LOW: 24, MEDIUM: 56, HIGH: 76, CRITICAL: 92 }[reviewRisk] : null);
  const checklist = useMemo(() => [{ label: "Code quality", good: !issues.some(i => risk(i.severity) === "HIGH") }, { label: "Security", good: !issues.some(i => /security|token|auth/i.test(`${issueText(i)} ${i.explanation || ""}`) && ["HIGH", "CRITICAL"].includes(risk(i.severity))) }, { label: "Error handling", good: !issues.some(i => /error|exception|fail/i.test(issueText(i))) }, { label: "Maintainability", good: true }, { label: "Test coverage", good: !issues.some(i => /test/i.test(issueText(i))) }], [issues]);
  if (loading) return <AppLayout title={`Pull Request #${pr}`}><LoadingState label="Loading changed files and review history…" /></AppLayout>;
  return <AppLayout title={`Pull Request #${pr}`} subtitle={`${owner} / ${repo} · Changed files and AI findings in one focused review workspace.`} actions={<><Link className="btn-secondary" to={`/repository/${owner}/${repo}`}>← Pull Requests</Link><button className="btn-primary" onClick={runReview} disabled={analyzing}>{analyzing ? "Analyzing…" : review ? "Run again" : "Start AI review"}</button></>}>
    {error && <div className="mb-6"><ErrorState message={error} retry={load} /></div>}
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1.18fr)_minmax(340px,.82fr)]">
      <section className="min-w-0"><div className="panel overflow-hidden"><div className="flex items-center justify-between border-b border-zinc-200 px-5 py-4"><h2 className="font-bold">Changed files <span className="text-zinc-500">{files.length}</span></h2><span className="mono text-xs text-zinc-500">Diff viewer</span></div>{files.length ? <div className="grid min-h-[580px] grid-cols-1 lg:grid-cols-[190px_minmax(0,1fr)]"><aside className="border-b border-zinc-200 bg-zinc-50 lg:border-b-0 lg:border-r"><ul className="max-h-56 overflow-auto lg:max-h-[580px]">{files.map((file, index) => <li key={file.filename}><button onClick={() => setSelected(index)} className={`w-full border-l-2 px-4 py-3 text-left text-xs ${selected === index ? "border-violet-600 bg-violet-50 text-violet-900" : "border-transparent text-zinc-600 hover:bg-zinc-100"}`}><span className="mono block truncate">{file.filename}</span><span className="mt-1 block text-[10px] text-teal-700">+{file.additions || 0} <span className="text-rose-700">−{file.deletions || 0}</span></span></button></li>)}</ul></aside><DiffFile file={currentFile} /></div> : <EmptyState title="No changed files found" body="This Pull Request does not have files available to review." />}</div></section>
      <aside className="space-y-5 xl:sticky xl:top-24 xl:self-start"><ReviewStatus analyzing={analyzing} review={review} score={score} level={reviewRisk} /><section className="panel p-5"><h2 className="font-bold">AI summary</h2><p className="mt-3 text-sm leading-6 text-zinc-600">{review?.overall_assessment || "Start an AI review to receive a structured summary of this Pull Request."}</p></section><section className="panel overflow-hidden"><div className="border-b border-zinc-200 px-5 py-4"><h2 className="font-bold">Findings <span className="text-zinc-500">{issues.length}</span></h2></div>{issues.length ? <div className="divide-y divide-zinc-200">{issues.map((issue, index) => <Finding key={`${issue.file || issue.filename}-${index}`} issue={issue} copy={async text => { await navigator.clipboard?.writeText(text); setCopied(`${index}`); setTimeout(() => setCopied(""), 1600); }} copied={copied === `${index}`} />)}</div> : <p className="p-5 text-sm text-zinc-600">{review ? "No specific findings were reported." : "Findings will appear here after analysis."}</p>}</section><section className="panel p-5"><h2 className="font-bold">Review checklist</h2><ul className="mt-3 space-y-2">{checklist.map(item => <li key={item.label} className="flex items-center gap-2 text-sm text-zinc-700"><span aria-label={item.good ? "Passed" : "Needs attention"} className={item.good ? "text-teal-600" : "text-amber-600"}>{item.good ? "✓" : "⚠"}</span>{item.label}</li>)}</ul></section>{history.length > 1 && <p className="px-1 text-xs text-zinc-500">{history.length} reviews saved for this Pull Request.</p>}</aside>
    </div>
  </AppLayout>;
}

function ReviewStatus({ analyzing, review, score, level }) { const steps = ["Fetching Pull Request", "Reading changed files", "Analyzing code", "Checking security", "Generating recommendations"]; return <section className="panel p-5"><div className="flex items-start justify-between gap-4"><div><p className="eyebrow">✦ AI Review</p><h2 className="mt-2 font-bold">{analyzing ? "Analyzing Pull Request" : review ? "Completed" : "Ready to analyze"}</h2></div>{review && <span className={`rounded-full px-2.5 py-1 text-xs font-bold ${riskStyles[level] || riskStyles.LOW}`}>{level} risk</span>}</div>{analyzing ? <ol className="mt-5 space-y-3">{steps.map((step, index) => <li key={step} className="flex items-center gap-3 text-sm text-zinc-600"><span className={index === 2 ? "h-3 w-3 animate-pulse rounded-full bg-violet-600" : "text-teal-600"}>{index < 2 ? "✓" : "○"}</span>{step}</li>)}</ol> : review ? <div className="mt-5 flex items-end gap-3"><strong className="text-4xl tracking-[-.06em]">{score}<small className="ml-1 text-base text-zinc-500">/ 100</small></strong><span className="mb-1 text-sm text-zinc-600">{level} risk</span></div> : <p className="mt-4 text-sm leading-6 text-zinc-600">Run a review to analyze code quality, security, maintainability, and risk.</p>}</section>; }
function Finding({ issue, copy, copied }) { const level = risk(issue.severity); const fix = issue.suggested_fix || issue.recommendation; return <article className="p-5"><div className="flex items-center justify-between gap-3"><span className={`rounded-full px-2 py-1 text-[10px] font-extrabold uppercase tracking-wide ${riskStyles[level] || riskStyles.INFO}`}>{level}</span><span className="mono truncate text-[10px] text-zinc-500">{issue.file || issue.filename || "Code"}{issue.line ? `:${issue.line}` : ""}</span></div><h3 className="mt-3 text-sm font-bold text-zinc-900">{issueText(issue)}</h3>{issue.explanation && <p className="mt-2 text-sm leading-6 text-zinc-600">{issue.explanation}</p>}{fix && <div className="mt-3 rounded-lg bg-violet-50 p-3"><p className="text-xs font-bold text-violet-900">Recommendation</p><p className="mt-1 text-xs leading-5 text-violet-800">{fix}</p><button onClick={() => copy(fix)} className="mt-2 text-xs font-bold text-violet-700">{copied ? "Copied ✓" : "Copy suggestion"}</button></div>}</article>; }
function DiffFile({ file }) { if (!file) return <div className="p-6 text-sm text-zinc-500">Select a file to view its changes.</div>; const lines = String(file.patch || "Patch preview is not available for this file.").split("\n"); return <div className="min-w-0 overflow-auto"><div className="flex items-center justify-between border-b border-zinc-200 px-5 py-3"><span className="mono truncate text-xs font-semibold">{file.filename}</span><span className="mono text-[10px] text-zinc-500">{file.status || "modified"}</span></div><pre className="mono m-0 min-w-[560px] p-4 text-xs leading-6 text-zinc-700">{lines.map((line, index) => <code key={`${line}-${index}`} className={`block rounded px-2 ${line.startsWith("+") ? "bg-teal-50 text-teal-900" : line.startsWith("-") ? "bg-rose-50 text-rose-900" : ""}`}><span className="mr-4 inline-block w-7 select-none text-right text-zinc-400">{index + 1}</span>{line || " "}</code>)}</pre></div>; }
